spring.application.name=reservehub

spring.datasource.url=jdbc:postgresql://localhost:5432/reservehub
spring.datasource.username=reservehub
spring.datasource.password=reservehub

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false